# base Image

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

# Set the working directory

WORKDIR /src

# Copy the project file and restore dependencies

COPY ["MyProject/Myproject.csproj", "MyProject/" ]

RUN  dotnet restore "MyProject/MyProject.csproj"

# Copy the rest of the application code

COPY . . 

# Build the application

RUN dotnet build "MyProject/MyProject.csproj" -c Release -o /app/build

# Publish the application

FROM build AS publish

RUN dotnet publish "MyProject/MyProject.csproj" -c Release -o /app/publish

# Now make the production file 

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final

# Set the working directory for the runtime image 

WORKDIR /app

# copy the published application from the publish stage

COPY  --from=publish /app/publish .

# Expose the port the app runs on 

EXPOSE 8080


# Command to run the application 

ENTRYPOINT ["dotnet", "MyProject.dll"]


